[package]
name = "lang"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = { version = "0.4.0", features = ["llvm17-0-prefer-static"] }
lru = "0.12.3"
pest = "2.7.10"
pest_derive = "2.7.10"
thiserror = "1.0.61"
